# Generated by Django 5.2.5 on 2025-08-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='matched_invoice',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='source_file',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='company',
            field=models.TextField(),
        ),
    ]
